
using System;
using System.Collections.Generic;
using DestinySharp;

namespace DestinySharp
{
    public class DestinyItemComponentSetOfint64
    {
public  DestinySharp.DictionaryComponentResponseOfint64AndDestinyItemInstanceComponent instances;
public  DestinySharp.DictionaryComponentResponseOfint64AndDestinyItemObjectivesComponent objectives;
public  DestinySharp.DictionaryComponentResponseOfint64AndDestinyItemPerksComponent perks;
public  DestinySharp.DictionaryComponentResponseOfint64AndDestinyItemRenderComponent renderData;
public  DestinySharp.DictionaryComponentResponseOfint64AndDestinyItemStatsComponent stats;
public  DestinySharp.DictionaryComponentResponseOfint64AndDestinyItemSocketsComponent sockets;
public  DestinySharp.DictionaryComponentResponseOfint64AndDestinyItemTalentGridComponent talentGrids;
public  DestinySharp.DictionaryComponentResponseOfuint32AndDestinyItemPlugComponent plugStates;
	}
}