
using System;
using System.Collections.Generic;
using DestinySharp;

namespace DestinySharp
{
    public class DestinyItemComponentSetOfint32
    {
public  DestinySharp.DictionaryComponentResponseOfint32AndDestinyItemInstanceComponent instances;
public  DestinySharp.DictionaryComponentResponseOfint32AndDestinyItemObjectivesComponent objectives;
public  DestinySharp.DictionaryComponentResponseOfint32AndDestinyItemPerksComponent perks;
public  DestinySharp.DictionaryComponentResponseOfint32AndDestinyItemRenderComponent renderData;
public  DestinySharp.DictionaryComponentResponseOfint32AndDestinyItemStatsComponent stats;
public  DestinySharp.DictionaryComponentResponseOfint32AndDestinyItemSocketsComponent sockets;
public  DestinySharp.DictionaryComponentResponseOfint32AndDestinyItemTalentGridComponent talentGrids;
public  DestinySharp.DictionaryComponentResponseOfuint32AndDestinyItemPlugComponent plugStates;
	}
}